### ISSUE TITLE
[bug] Triggered job has no build parameters defined

### ISSUE THREAD

**Issue by sdatko** [jenkinsci/urltrigger-plugin#37] opened 2021-01-21 17:25 UTC
Hello,

we observed there is a bug in URLTrigger that causes it to ignore build parameters defined for jobs. Each triggered build is launched like there were no parameters defined, while jobs triggered by other plugins (in our case: Gerrit Trigger) have such parameters with their default values set.

**Versions**:
– Jenkins: 2.263.2
– URLTrigger: 0.48
– Java: jre8-openjdk / 8.u275

**Steps to reproduce**:
1) Create a new job, can be project type or pipeline.
2) Check the "This build is parameterized" option and define any parameter with some default value.
3) Check the "URLTrigger" option.
a) Add any URL to monitor (you can use [https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h](https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h) for convenience).
b) Set "Inspect URL content" option and choose "Monitor a change of the content".
c) Set the schedule to `* * * * *` (every minute).
4) Add a step in the job to print the environment variables (`env` call in shell).
5) Wait for the URLTrigger to run the build.
6) Launch the build also by hand for comparison.

**Result**:
No build parameters were added to the triggered build. Notice no parameter in `env` call's output from the job step and no "Parameters" button on the side menu when browsing the build result.

**Expected behavior**:
There should be build parameters available, as it is when job is launched by hand (build button) or other triggers.

**Possible workarounds for now**:
– Create additional job that will be triggered by URLTrigger plugin and use it to invoke the desired job.
– Add a step where you verify your job parameters and redefine them if necessary.

Yours,
Szymon

**Comment by TonyNoble** [comment] 2021-12-02 13:28
Many thanks for the bug report

Duplicate of #36 - closing.

**Closed by TonyNoble** 2021-12-02 13:28 UTC
