### ISSUE TITLE
The triggered job is parameterized, but the default values are not used

### ISSUE THREAD

**Issue by jdjamsa1** [jenkinsci/urltrigger-plugin#36] opened 2021-01-16 00:02 UTC
So if I use this plugin to trigger my job based on the content of some url, my job DOES get triggered but does not use the default parameter values that have been specified for it.  Is that what you would expect?

**Comment by sdatko** [comment] 2021-01-21 17:27
Hey, 

I noticed this as well and for me this is definitely a bug. I explained why and described the steps to reproduce the bug, here: [https://github.com/jenkinsci/urltrigger-plugin/issues/37](https://github.com/jenkinsci/urltrigger-plugin/issues/37).

Yours, 
Szymon

**Comment by TonyNoble** [comment] 2021-12-02 13:34
This was due to an issue with xtrigger-lib, caused by the changes to parameterised jobs in Jenkins.

Resolved with release 0.50 of URLTrigger plugin

**Closed by TonyNoble** 2021-12-02 13:34 UTC
