### ISSUE TITLE
Poll with a URL is not working

### ISSUE THREAD

**Issue by Vinoddogra** [jenkinsci/urltrigger-plugin#42] opened 2021-10-28 09:50 UTC
poll with the url is not getting changes inside the folder
I am using Jenkins Build Trigger [URLTrigger] - Poll with a URL  (version (0.47)

Inspecting Monitor a change of the content content for URL 
https://subversion.xxxxxx.com/svn/branches/VTX-1951_ArtifacTesting/Vaisala.VTX/

Polling started on Oct 28, 2021 12:40:29 PM
Polling for the job VTX-1951-VTX2_Core_Af
Looking nodes where the poll can be run.
Looking for a candidate node to run the poll.
Trying to find an eligible node with the assigned project label vtx2-02.

Polling remotely on hel-vtx2-02
Resolving environment variables using global values
Invoking the url: 
 https://subversion.xxxxxx.com/svn/branches/VTX-1951_ArtifacTesting/Vaisala.VTX/

Polling complete. Took 0.14 sec.
No changes.

**Comment by TonyNoble** [comment] 2021-12-02 13:37
Hi @Vinoddogra 

Can provide some detail on the job configuration and Jenkins version?

Also, the plugin is now at version 0.50 - I'd recommend updating and retesting as a first step.

**Comment by paride** [comment] 2022-05-17 15:51
@Vinoddogra could it be that you're hitting https://issues.jenkins.io/browse/JENKINS-24073?

**Comment by TonyNoble** [comment] 2022-11-02 10:16
No update in 12 months and plugin has moved on significantly since then.  Closing.

**Closed by TonyNoble** 2022-11-02 10:16 UTC

**Comment by paride** [comment] 2022-11-02 10:23
@TonyNoble I believe this is a duplicate of https://issues.jenkins.io/browse/JENKINS-24073 which is not fixed as far as I can tell.

**Comment by TonyNoble** [comment] 2022-11-02 11:26
Hi @paride 

I'm not sure that issue is still valid - I've not been able to reproduce it for as long as I can remember and the codebase has moved on tremendously since then.  If you can reproduce with an up-to-date Jenkins and plugin version, please open a new issue here with the details, it would be much appreciated (the confluence stuff is a bit of a mess in general - I really only look at the GitHub issues these days)
